# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrimata_app', '0002_auto_20161221_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='min_investment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_gain_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_volatility',
            field=models.IntegerField(default=0),
        ),
    ]
