# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrimata_app', '0003_auto_20161221_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='min_investment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_gain_loss',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_volatility',
            field=models.CharField(default='', max_length=100),
        ),
    ]
