# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrimata_app', '0004_auto_20161221_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='min_investment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_gain_loss',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_volatility',
            field=models.CharField(max_length=100),
        ),
    ]
