# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chrimata_app', '0005_auto_20161221_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chrimata_app.Investment'),
        ),
    ]
